# Site settings
title: Sh4d3-Pwn3r # site title
description: >- # site description
  I'm 21 y/o, only interested in RedTeaming, I made this blog to sharing my knowlage and what I learned  about CyberSecurity with you, I hope it will be useful.
lang: en-US # default lang
timezone: Africa/Egypt # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/Sh4d3-Pwn3r/sh4d3-pwn3r.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Sh4d3-Pwn3r # author name
  bio: >- # tell to the world
    I'm 21 y/o, only interested in RedTeaming, I made this blog to sharing my knowlage and what I learned  about CyberSecurity with you, I hope it will be useful, 
    meet Sh4d3-Pwn3r at <a href="https://github.com/Sh4d3-Pwn3r" target="_blank" rel="noopener">@github</a>.
  username: Sh4d3-Pwn3r # general username
  github: Sh4d3-Pwn3r # github username
  #twitter: twitter_username # twitter username
  #facebook: facebook_username # facebook username
  #email: your-email@email.com # email adress
  avatar: https://i.imgur.com/YBvWC7E.png # change with your own avatar

# URL settings
url: "https://sh4d3-pwn3r.github.io/" #
baseurl: '/'
permalink: /:title/
google_analytics:
  id: 'G-PF0YFHP4G2'          # Fill with your Google Analytics ID
  pv:
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    enabled: false
    # the next options only valid when `google_analytics.pv` is enabled.
    proxy_url: ''
    proxy_endpoint: ''
    cache: false  # pv data local cache, good for the users from GFW area.
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
